//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.22 at 02:12:40 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://login.e2eapp.umesolutions.com/UserLoginService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.umesolutions.e2eapp.login.userloginservice;
